---
- name: Ensure Horizon Packages are Installed
  apt:
    name:
      - openstack-dashboard
    state: latest

- name: Set up Apache for Horizon
  template:
    src: openstack-dashboard.conf.j2
    dest: /etc/apache2/sites-available/openstack-dashboard.conf

- name: Configure Horizon Parameters
  template:
    src: local_settings.py.j2
    dest: /etc/openstack-dashboard/local_settings.py

- name: Restart Apache Service
  service:
    name: apache2
    state: restarted
